openapi: "3.0.0"
info:
  title: Wallet API
  description: Wallet Management API
  version: v0.0.1
  contact:
    name: Maluki Muthusi Maluki
    url: https://twitter.com/MalukiMuthusi
    email: malukimuthusi@gmail.com

servers:
  - url: https://wallet-api-fur355ca3q-uc.a.run.app/v1
    description: Staging server
  - url: https://api.wallet.riviatechs.com/v1
    description: Production server

paths:
  /wallets/{wallet_id}/balance:
    get:
      summary: Returns a wallet's balance amount
      description: Returns the balance of the wallet that has the provided id
      operationId: GetBalance
      parameters:
        - $ref: "#/components/parameters/wallet_id"
      responses:
        "200":
          description: The returned balance amount
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Wallet"

        "422":
          description: Invalid value provided for the wallet id
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InvalidWalletIdParam"

        "404":
          description: Wallet not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WalletNotFound"

        "500":
          description: Server encountered error when processing your request. This a server error. When in debugging session check the response to see what happened to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

        "501":
          description: The operation has not been implemented yet.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotImplementedError"

  /wallets/{wallet_id}/credit:
    post:
      summary: Add an amount to a wallet
      description: Adds the provided amount to the wallet that is referred by the provided id
      operationId: CreditWallet
      parameters:
        - $ref: "#/components/parameters/wallet_id"
      requestBody:
        description: The amount to be added to the account
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Amount"
      responses:
        "200":
          description: Returns the new balance of the wallet
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Wallet"

        "404":
          description: Wallet not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WalletNotFound"

        "422":
          description: Server could not process your request. Check the response for the error code and the message to see where the probelm is
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/InvalidAmount"
                  - $ref: "#/components/schemas/InvalidWalletIdParam"

        "500":
          description: Server encountered error when processing your request. This a server error. When in debugging session check the response to see what happened to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

        "501":
          description: The operation has not been implemented yet.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotImplementedError"

  /wallets/{wallet_id}/debit:
    post:
      summary: Subtracts an amount from  a wallet
      description: Subtracts the given amount from the wallet referred by the provided wallet id
      operationId: DebitWallet
      parameters:
        - $ref: "#/components/parameters/wallet_id"
      requestBody:
        description: The amount to be subtracted from the account
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Amount"

      responses:
        "200":
          description: Returns the new balance of the wallet
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Wallet"

        "404":
          description: Wallet not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WalletNotFound"

        "422":
          description: Server could not process your request. Check the response for the error code and the message to see where the probelm is
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/InvalidAmount"
                  - $ref: "#/components/schemas/InvalidWalletIdParam"

        "500":
          description: Server encountered error when processing your request. This a server error. When in debugging session check the response to see what happened to the server
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InternalServerError"

        "501":
          description: The operation has not been implemented yet.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotImplementedError"

components:
  schemas:
    Amount:
      type: object
      properties:
        value:
          type: string
        currency:
          type: string
          default: EUR
          enum:
            - EUR

    Wallet:
      type: object
      properties:
        balance:
          type: string

    BasicError:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          enum:
            - INSUFFICIENT_FUNDS
            - INVALID_WALLET_ID_PARAM
            - WALLET_NOT_FOUND
            - FAILED_TO_PROCESS_REQUEST
            - REQUEST_NOT_ALLOWED
            - INTERNAL_SERVER_ERROR
            - NOT_IMPLEMENTED
            - INTERNAL_SERVER_ERROR
            - INVALID_AMOUNT
        message:
          type: string

    InvalidAmount:
      type: object
      properties:
        code:
          type: string
          default: INVALID_AMOUNT
        message:
          type: string
          default: provide a valid amount value

    InvalidWalletIdParam:
      type: object
      properties:
        code:
          type: string
          default: INVALID_WALLET_ID_PARAM
        message:
          type: string
          default: provide a valid wallet id parameter in the request

    WalletNotFound:
      type: object
      properties:
        code:
          type: string
          default: WALLET_NOT_FOUND
        message:
          type: string
          default: provide a valid wallet id parameter in the request

    InternalServerError:
      type: object
      properties:
        code:
          type: string
          default: INTERNAL_SERVER_ERROR
        message:
          type: string
          default: failed to complete processing request

    NotImplementedError:
      type: object
      properties:
        code:
          type: string
          default: NOT_IMPLIMENTED
        message:
          type: string
          default: operation not implemented on the server

  parameters:
    wallet_id:
      name: wallet_id
      in: path
      description: Refers to a wallet by its id
      required: true
      schema:
        type: integer
        format: int32
