openapi: 3.0.0
info:
  title: Wallet API
  description: Wallet API
  version: 0.0.1

servers:
  - url: http://api.example.com/v1/wallets

paths:
  /{wallet_id}/balance:
    get:
      summary: Returns a wallet's balance
      description: Returns the balance of the wallet that has the provided ID
      responses:
        "200":
          description: Contains the balance amount
          content:
            application/json:
              schema:
                type: number

  /{wallet_id}/credit:
    post:
      requestBody:
        description: The amount to be added to the account
        required: true
        content:
          application/json:
            schema:
              type: number
      responses:
        "200":
          description: Returns the new balance of the wallet
