/*
 * Wallet API
 *
 * Wallet Management API
 *
 * API version: v0.0.1
 * Contact: malukimuthusi@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type Balance struct {
	Value string `json:"value,omitempty"`
	// Only one currency type is currently supported, euro
	Currency string `json:"currency,omitempty"`
	Date string `json:"date"`
}
