/*
 * Wallet API
 *
 * Wallet Management API
 *
 * API version: v0.0.1
 * Contact: malukimuthusi@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package models

type BasicError struct {
	Code string `json:"code"`
	Message string `json:"message"`
}
